### ISSUE TITLE
EpStatusId enum values doesn't match EpStatusType in api.yml

### ISSUE THREAD

**Issue by EverettSummer** [bangumi/api#122]
Could you tell me what each value of EpStatusId represented? why the order is not a natural order?
```
    EpStatusId:
      description: 章节状态 ID
      type: integer
      enum:
        - 2
        - 1
        - 3
    EpStatusType:
      description: 章节状态类型
      type: string
      enum:
        - watched
        - queue
        - drop
        - remove
```
