### ISSUE TITLE
`管理收藏`api的实际行为与文档不符

### ISSUE THREAD

**Issue by Trim21** [bangumi/api#40]
现在只有在`content-type`为`multipart/form-data` 或者`application/x-www-form-urlencoded`的情况下,把`status`做为body才能修改状态

无论是在`content-type: application/json`的情况下做为body,还是放在queryString中均会导致状态变成`wish`

但是文档里 是直接放在url里的...

**Comment by Trim21** [comment]
`看到本集`的api也是...
文档里也是挡在了query string中- -

**Comment by Trim21** [comment]
把文档中的`  securitySchemes`字段修改为如下,然后找个浏览器跨域插件,就可以在文档页面成功调用api了
```yaml
    bangumi_auth:
      type: http
      scheme: bearer
```
在这种情况下,api调用结果也是错误的..
会清空观看进度
